[package]
name = "cipher"
version = "0.1.0"
edition = "2021"

[lib]
name = "cipher"
path = "src/lib.rs"

[dependencies]
rand ="0.9.0"
clap = { version = "4.0.30", features = ["derive"] }
itertools = "0.14.0"
